# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.CharField(choices=[('CC36', 'Crimp Center 36'), ('CC64', 'Crimp Center 64'), ('LOFF', 'LockOff Station'), ('A-1', 'A-1'), ('DLab', 'DynaLab'), ('Twist', 'Twister'), ('USonic', 'Ultra Sonic'), ('pnsys', 'Pneumatic System'), ('sboard', 'Smart Board'), ('tpost', 'Tool Post'), ('ecut3300', 'Eco Cut 3300'), ('UCrimp', 'UniCrimp 220'), ('Mp104', 'Mecal P-104 press'), ('slice', 'Slice AMTI'), ('FumeEx', 'Fume Extractors'), ('UPS', 'UPS'), ('other', 'other')], max_length=15)),
                ('prioritynum', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('hold', 'HOLD'), ('wait', 'WAIT')], max_length=4)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('wip', 'In Progress'), ('cancelled', 'Canceled'), ('Complete', 'Complete')], max_length=10)),
                ('issue_kind', models.CharField(choices=[('Quality', 'Quality Issue'), ('MachineD', 'Machine Down'), ('Software', 'Software'), ('Mechanical', 'Mechanical'), ('Pneumatic', 'Pnuematic'), ('Electrical', 'Electrical'), ('Setup', 'Setup'), ('Maintenance', 'Maintenance'), ('Warehouse', 'Warehouse'), ('Assembly', 'Assembly')], max_length=15)),
                ('issue_desc', models.TextField(max_length=300)),
                ('tech_name', models.CharField(choices=[('Evan', 'Evan'), ('Terell', 'Terell'), ('Tony', 'Tony'), ('Other', 'Other')], max_length=10)),
                ('timespent', models.DecimalField(decimal_places=0, max_digits=6)),
                ('resolution_desc', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
